# Generated by Django 4.0.4 on 2022-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputEmpresa', models.CharField(max_length=50)),
                ('inputEmail', models.EmailField()),
                ('inputTel', models.IntegerField()),
                ('inputCel', models.IntegerField()),
                ('inputAddress', models.CharField(max_length=50)),
                ('inputNumber', models.IntegerField()),
                ('inputAddress2', models.CharField(max_length=30)),
                ('inputCEP', models.IntegerField()),
                ('inputCity', models.CharField(max_length=30)),
                ('inputEstado', models.CharField(max_length=20)),
            ],
        ),
    ]
