# Generated by Django 4.0.4 on 2022-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pji2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='inputCEP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputCel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputTel',
            field=models.IntegerField(),
        ),
    ]
