# Generated by Django 4.0.4 on 2022-05-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pji2app', '0002_alter_cadastro_inputcep_alter_cadastro_inputcel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='inputEmail',
            field=models.CharField(max_length=50),
        ),
    ]
