# Generated by Django 4.0.4 on 2022-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pji2app', '0004_alter_cadastro_inputcep_alter_cadastro_inputcel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='inputAddress',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputAddress2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputCEP',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputCel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputCity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputEmail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputEmpresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputEstado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inputTel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
