# Generated by Django 4.0.4 on 2022-05-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pji2app', '0007_cadastro_inputcnpj_alter_cadastro_inputaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='inputCNPJ',
        ),
    ]
