# Generated by Django 4.0.4 on 2022-05-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pji2app', '0008_remove_cadastro_inputcnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='inputCNPJ',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
